version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
    image: php:8.2-apache
    volumes:
      - ./app:/var/www/html